Repository Developer-DAO/academy-turbo, pull requests merged in 2024-01, with the labels that each got.

#47 Feat/v2 mvp working mdx
  apps/academy/next.config.js
  apps/academy/next.config.mjs
  apps/academy/package.json
  apps/academy/src/components/LessonLayout.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/contexts/AppContext.tsx
  apps/academy/src/contexts/AppContextProvider.tsx
  apps/academy/src/pages/_app.tsx
  apps/academy/src/pages/intro-to-ethereum/1.mdx
  apps/academy/src/server/api/root.ts
  apps/academy/src/server/api/routers/completedquizzes.ts
  apps/academy/src/server/api/routers/lessons.ts
  packages/database/index.ts
  packages/database/prisma/schema.prisma
  packages/next-config/nextpwamdx.config.mjs
  packages/next-config/package.json
  pnpm-lock.yaml
Labels: enhancement

#48 feat: migrated quiz component and related dependencies
  apps/academy/src/components/AboutCourse.tsx
  apps/academy/src/components/Header.tsx
  apps/academy/src/components/LessonLayout.tsx
  apps/academy/src/components/mdx/Components.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/components/mdx/SideDrawer.tsx
  apps/academy/src/contexts/AppContextProvider.tsx
  apps/academy/src/pages/_app.tsx
  apps/academy/src/pages/intro-to-ethereum/1.mdx
  apps/academy/src/pages/intro-to-ethereum/2.mdx
  apps/academy/src/pages/intro-to-ethereum/3.mdx
  apps/academy/src/pages/track/[trackID].tsx
  apps/academy/src/server/api/root.ts
  packages/database/index.ts
  packages/database/prisma/schema.prisma
  packages/database/prisma/seed.ts
  packages/ui/package.json
  packages/ui/src/components/Button/Button.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/ui/badge.tsx
  packages/ui/src/components/ui/dialog.tsx
  packages/ui/src/components/ui/drawer.tsx
  packages/ui/src/components/ui/toast.tsx
  packages/ui/src/components/ui/toaster.tsx
  packages/ui/src/components/ui/use-toast.tsx
  pnpm-lock.yaml
Labels: enhancement

#49 feat: some small css fixes and enhancements
  apps/academy/src/components/LessonLayout.tsx
  apps/academy/src/components/mdx/Quiz.tsx
Labels: enhancement

#51 Feat/styling fixes
  README.md
  TODO.md
  apps/academy/public/fundamental-bg.jpeg
  apps/academy/public/icon-192x192.png
  apps/academy/public/icon-256x256.png
  apps/academy/public/icon-384x384.png
  apps/academy/public/icon-512x512.png
  apps/academy/public/maskable_icon.png
  apps/academy/public/maskable_icon_x48.png
  apps/academy/src/components/AboutCourse.tsx
  apps/academy/src/components/Header.tsx
  apps/academy/src/components/Layout.tsx
  apps/academy/src/components/TracksLayout.tsx
  apps/academy/src/pages/track/[trackID].tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  packages/ui/src/components/Banners/PartnerBanner.tsx
  packages/ui/src/components/Cards/TrackCard.tsx
  packages/ui/src/components/Footer/Footer.tsx
  packages/ui/src/styles.css
Labels: enhancement

#52 feat: fixed footer links among other small stuff
  apps/academy/src/components/Header.tsx
  packages/ui/package.json
  packages/ui/src/components/Footer/Footer.tsx
  packages/ui/src/components/Topbar/TopBar.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/ui/tooltip.tsx
  pnpm-lock.yaml
Labels: enhancement

#53 Feat/nft track imported
  TODO.md
  apps/academy/src/components/mdx/Components.tsx
  apps/academy/src/components/mdx/Contributor.tsx
  apps/academy/src/components/mdx/ContributorFooter.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/data/contributors.ts
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
Labels: enhancement

#55 feat: enhanced tracks layout and layout header and footer mobile styles
  apps/academy/src/components/Header.tsx
  apps/academy/src/components/Layout.tsx
  apps/academy/src/components/TrackAuthor.tsx
  apps/academy/src/components/TracksLayout.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
Labels: enhancement

#56 feat: add erc-20 track, fixed tags styling
  apps/academy/src/components/AboutCourse.tsx
  apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/index.tsx
Labels: enhancement

#57 feat: trackspage and trackpage layout responsive mobile enhancements
  apps/academy/src/components/AboutCourse.tsx
  apps/academy/src/components/LessonLayout.tsx
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
Labels: enhancement

#60 feat: Update Content: Re-order fundamental, update authors, and enhance descriptions
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/fundamentals/cli_lesson.mdx
  apps/academy/src/pages/tracks/fundamentals/code-editors.mdx
  apps/academy/src/pages/tracks/fundamentals/connect-with-rpc.mdx
  apps/academy/src/pages/tracks/fundamentals/decentralized-storage.mdx
  apps/academy/src/pages/tracks/fundamentals/index.tsx
  apps/academy/src/pages/tracks/fundamentals/install-npm.mdx
  apps/academy/src/pages/tracks/fundamentals/nft-hosting.mdx
  apps/academy/src/pages/tracks/fundamentals/open_zeppelin.mdx
  apps/academy/src/pages/tracks/fundamentals/testnets.mdx
  apps/academy/src/pages/tracks/fundamentals/token-standards.mdx
  apps/academy/src/pages/tracks/fundamentals/wallets.mdx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/4.mdx
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
Labels: documentation, enhancement

#64 feat: update/create remaining titles/descriptions for tracks/lessons
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/fundamentals/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
Labels: documentation, ready to review

#65 feat: fixed bad quizzes paths on all tracks folder lessons
  TODO.md
  apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/intro-to-ethereum/1.mdx
  apps/academy/src/pages/tracks/intro-to-ethereum/2.mdx
  apps/academy/src/pages/tracks/intro-to-ethereum/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/4.mdx
Labels: enhancement

#70 feat: Quiz component styling + created LessonQuestionsModal & LessonInformationalModal(WIP)
  apps/academy/src/components/AboutCourse.tsx
  apps/academy/src/components/Header.tsx
  apps/academy/src/components/TracksLayout.tsx
  apps/academy/src/components/mdx/Components.tsx
  apps/academy/src/components/mdx/LessonInformationalModal.tsx
  apps/academy/src/components/mdx/LessonQuestionsModal.tsx
  apps/academy/src/components/mdx/Question.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/pages/_app.tsx
  apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/fundamentals/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/4.mdx
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
  apps/academy/src/server/api/routers/completedquizzes.ts
  apps/academy/src/styles.css
  apps/academy/src/utils/QuizHelpers.ts
  packages/ui/src/components/Cards/TrackCard.tsx
Labels: enhancement

#71 feat: update description tags on lessons and tracks
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/fundamentals/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
Labels: documentation

#73 chore: Fix paths to some lessons. Prompt learner to take breaks
  apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/intro-to-ethereum/1.mdx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/4.mdx
Labels: hotfix

#74 feat: NFT track/Connect to Front-end lesson: add warm-up quiz
  apps/academy/src/data/questions/lesson-5/1-intro/Q1.json
  apps/academy/src/data/questions/lesson-5/1-intro/Q2.json
  apps/academy/src/data/questions/lesson-5/1-intro/Q3.json
  apps/academy/src/data/questions/lesson-5/1-intro/Q4.json
  apps/academy/src/data/questions/lesson-5/1-intro/Q5.json
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
Labels: enhancement, ready to review

#87 feat: final quiz for NFT-Front-end lesson 5
  apps/academy/src/data/quizzes/nft-solidity/quiz-nft-solidity-5.json
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
Labels: enhancement

#97 feat: fixed branch afte running pnpm install
  pnpm-lock.yaml
Labels: enhancement

#98 Feat/wallet connect fixed
  apps/academy/package.json
  apps/academy/src/components/ConnectButton.tsx
  apps/academy/src/data/quizzes/nft-solidity/quiz-nft-solidity-5.json
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
  packages/ui/package.json
  packages/ui/src/components/SideBar/SideBar.tsx
  pnpm-lock.yaml
Labels: enhancement

#94 chore: replace Metamask references with Zerion in Academy
  apps/academy/public/assets/lessons/wallets/MM_for_Brave.png
  apps/academy/public/assets/lessons/wallets/wallet_choices.png
  apps/academy/public/assets/lessons/wallets/zerion-ext-download.png
  apps/academy/src/pages/tracks/fundamentals/wallets.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
Labels: content

#102 feat: fixed avatar, fixed question modal and added footer D_D url
  apps/academy/src/components/ConnectButton.tsx
  apps/academy/src/components/mdx/LessonQuestionsModal.tsx
  packages/ui/src/components/Footer/Footer.tsx
Labels: enhancement

#101 feat: set up PR to change RPC to Partners
  apps/academy/public/assets/lessons/connect-with-rpc/networks4.png
  apps/academy/public/assets/lessons/connect-with-rpc/ropsten-RPC-metamask.png
  apps/academy/public/assets/lessons/connect-with-rpc/sepolia-network-info-zerion.png
  apps/academy/public/assets/lessons/connect-with-rpc/test-networks-zerion.png
  apps/academy/src/pages/tracks/fundamentals/connect-with-rpc.mdx
Labels: documentation, content

#114 Feat/seeder
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  package.json
  packages/database/package.json
  packages/database/prisma/seed.ts
  pnpm-lock.yaml
Labels: enhancement

#115 feat: commiting minor changes and seeder code example update
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
  packages/database/prisma/seed.ts
Labels: enhancement

#119 feat: update 2 out of 3 lessons with POKT rpc providers
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
Labels: documentation, ready to review, content, mvp
