Repository Developer-DAO/academy-turbo, pull requests merged in 2024-02, with the labels that each got.

#116 feat: backend integration and created a small spinner component
  apps/academy/src/components/Spinner.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/contexts/AppContext.tsx
  apps/academy/src/contexts/AppContextProvider.tsx
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/fundamentals/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
  apps/academy/src/server/api/root.ts
  apps/academy/src/server/api/routers/lessons.ts
  apps/academy/src/server/api/routers/tracks.ts
  packages/database/prisma/schema.prisma
  packages/database/prisma/seed.ts
  packages/ui/src/components/Cards/TrackCard.tsx
Labels: enhancement

#122 feat: commented code to avoid errors
  apps/academy/src/contexts/AppContext.tsx
  apps/academy/src/contexts/AppContextProvider.tsx
Labels: enhancement

#124 fix: new track placeholder imgs
  .gitignore
  apps/academy/public/track-erc20.png
  apps/academy/public/track-erc721.png
  apps/academy/public/track-fundamentals.png
  apps/academy/public/track-intro-eth.png
Labels: enhancement

#125 feat: fixed blurried images on Cards components and more small fixes
  apps/academy/public/landing-page-screenshot.png
  apps/academy/src/pages/tracks/index.tsx
  packages/database/prisma/seed.ts
  packages/ui/src/components/Cards/TrackCard.tsx
Labels: enhancement

#127 Feat/img banner fix
  packages/ui/src/components/Cards/TrackCard.tsx
Labels: enhancement

#129 feat: including tags tracks on tracks list page
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/server/api/routers/tracks.ts
Labels: enhancement

#130 feat: fixed quiz functionality and deleted unnused folder
  apps/academy/src/components/mdx/Question.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/content/intro-to-ethereum/1.mdx
  apps/academy/src/content/intro-to-ethereum/2.mdx
  apps/academy/src/content/intro-to-ethereum/3.mdx
  apps/academy/src/data/quizzes/nft-solidity/quiz-nft-solidity-1.json
  apps/academy/src/server/api/routers/completedquizzes.ts
  apps/academy/src/server/auth.ts
  packages/database/prisma/schema.prisma
Labels: enhancement

#134 feat: new prisma schema tables with visible boolean tags
  apps/academy/.env.example
  apps/academy/src/env.mjs
  apps/academy/src/server/api/routers/lessons.ts
  apps/academy/src/server/api/routers/tracks.ts
  packages/database/prisma/schema.prisma
Labels: enhancement

#143 feat: tracks cards banner images
  apps/academy/public/track-erc20.png
  apps/academy/public/track-erc721.png
  apps/academy/public/track-fundamentals.png
  apps/academy/public/track-intro-eth.png
Labels: enhancement

#144 feat: adding banner image
  apps/academy/public/image16.png
Labels: enhancement, mvp

#145 feat: theme toggle button hided and abstracted in a new component
  apps/academy/src/components/Header.tsx
  apps/academy/src/components/ThemeToggleButton.tsx
Labels: enhancement, mvp

#146 Feat/community icon
  packages/ui/src/components/Icons.tsx
Labels: enhancement, mvp

#147 feat: updated code to run deploy
  apps/academy/src/components/Header.tsx
  packages/ui/src/components/Topbar/TopBar.tsx
Labels: enhancement, mvp

#148 fix: typo
  apps/academy/src/components/Header.tsx
Labels: enhancement

#153 Feat/seed data
  packages/database/data/allLessonsData.ts
  packages/database/data/allTagsData.ts
  packages/database/data/allTagsOnLessonsData.ts
  packages/database/data/allTagsOnTracksData.ts
  packages/database/data/allTracksData.ts
  packages/database/prisma/seed.ts
  packages/database/tsconfig.json
Labels: enhancement

#157 chore: remove pomodoro references.
  apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/4.mdx
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
Labels: ready to review, content

#156 chore: pin openzeppelin version. update lesson text/screenshots
  apps/academy/public/assets/lessons/3/4_deploy-tierNFT.png
  apps/academy/public/assets/lessons/3/4_deploy.png
  apps/academy/public/assets/lessons/3/5_mint-tierNFT.png
  apps/academy/public/assets/lessons/3/5_mint.png
  apps/academy/public/assets/lessons/3/6_tierNFTs.png
  apps/academy/public/assets/lessons/3/6_tiernfts_opensea.png
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
Labels: ready to review, content

#155 Feat: new quiz sucess modals & more improvements
  .env.example
  apps/academy/.env.example
  apps/academy/public/happy_face.png
  apps/academy/src/components/mdx/Components.tsx
  apps/academy/src/components/mdx/LessonInformationalModal.tsx
  apps/academy/src/components/mdx/LessonQuestionsModal.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/components/mdx/QuizCompletedModals.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/contexts/AppContext.tsx
  apps/academy/src/contexts/AppContextProvider.tsx
  apps/academy/src/interfaces/index.ts
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
  apps/academy/src/server/api/routers/tracks.ts
  packages/database/prisma/seed.ts
  packages/ui/src/components/Cards/TrackCard.tsx
  packages/ui/src/components/SideBar/SideBar.tsx
  packages/ui/src/styles.css
Labels: enhancement, ready to review, mvp

#162 feat: mvp fixes
  apps/academy/src/components/mdx/LessonInformationalModal.tsx
  apps/academy/src/components/mdx/Question.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/components/mdx/QuizCompletedModals.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/pages/index.tsx
  packages/ui/src/components/Banners/LearnWeb3Banner.tsx
  packages/ui/src/components/Banners/PartnerBanner.tsx
  packages/ui/src/components/Footer/Footer.tsx
Labels: enhancement, mvp

#165 Feat/fundamentals page
  apps/academy/public/bg_fundamentals.png
  apps/academy/public/homepage-seo-screenshot.png
  apps/academy/src/components/Header.tsx
  apps/academy/src/components/Layout.tsx
  apps/academy/src/components/mdx/Quiz.tsx
  apps/academy/src/components/mdx/QuizStatusChecker.tsx
  apps/academy/src/pages/fundamentals/index.tsx
  apps/academy/src/pages/tracks/fundamentals/index.tsx
Labels: enhancement

#181 feat: add content contributor avatar images
  apps/academy/public/authors/7i7o.jpg
  apps/academy/public/authors/brianfive.jpg
  apps/academy/public/authors/john-mac.jpg
  apps/academy/public/authors/piablo.png
  apps/academy/public/authors/ropats16.jpg
  apps/academy/src/pages/tracks/erc-20-solidity/1.mdx
  apps/academy/src/pages/tracks/erc-20-solidity/2.mdx
  apps/academy/src/pages/tracks/fundamentals/cli_lesson.mdx
  apps/academy/src/pages/tracks/fundamentals/code-editors.mdx
  apps/academy/src/pages/tracks/fundamentals/connect-with-rpc.mdx
  apps/academy/src/pages/tracks/fundamentals/decentralized-storage.mdx
  apps/academy/src/pages/tracks/fundamentals/install-npm.mdx
  apps/academy/src/pages/tracks/fundamentals/nft-hosting.mdx
  apps/academy/src/pages/tracks/fundamentals/open_zeppelin.mdx
  apps/academy/src/pages/tracks/fundamentals/testnets.mdx
  apps/academy/src/pages/tracks/fundamentals/token-standards.mdx
  apps/academy/src/pages/tracks/fundamentals/wallets.mdx
  apps/academy/src/pages/tracks/nft-solidity/1.mdx
  apps/academy/src/pages/tracks/nft-solidity/2.mdx
  apps/academy/src/pages/tracks/nft-solidity/3.mdx
  apps/academy/src/pages/tracks/nft-solidity/4.mdx
  apps/academy/src/pages/tracks/nft-solidity/5.mdx
Labels: ready to review, design

#182 feat: created new api request method
  apps/academy/src/server/api/routers/lessons.ts
Labels: enhancement

#187 feat: added PageSEOLayout for all pages, lessons pages remaining
  apps/academy/src/pages/404.tsx
  apps/academy/src/pages/fundamentals/index.tsx
  apps/academy/src/pages/index.tsx
  apps/academy/src/pages/tracks/erc-20-solidity/index.tsx
  apps/academy/src/pages/tracks/index.tsx
  apps/academy/src/pages/tracks/intro-to-ethereum/index.tsx
  apps/academy/src/pages/tracks/nft-solidity/index.tsx
  apps/academy/src/pages/tracks/oracles-api3/index.tsx
  apps/academy/src/pages/tracks/web3-python/index.tsx
Labels: enhancement

#192 feat: adding vercel analytics
  apps/academy/package.json
  apps/academy/src/pages/_app.tsx
  pnpm-lock.yaml
Labels: enhancement

#211 Staging to Main: adding vercel analytics
  apps/academy/package.json
  apps/academy/src/pages/_app.tsx
  pnpm-lock.yaml
Labels: enhancement
